### ISSUE TITLE
Can't install some versions in macOS

### ISSUE THREAD

**Issue by sys9kdr** [Fbrisset/asdf-pandoc#7]
**Describe the bug**

Currently, we can't install some versions of Pandoc(e.g. 3.1.2) in macOS.

**Steps to reproduce**

1. `asdf install pandoc@3.1.2`
2. Download failure

**Expected behavior**

Download correctly

**Screenshots**

**Additional context**

Maybe, we can't install many other versions in macOS.

**Comment by Fbrisset** [comment]
@sys9kdr Please try `uname -a` and give me the result.

**Comment by Fbrisset** [comment]
Check if on branch #9, if everything is OK for MacOS.(the code will be clean later) (I have no adequate macos env to test more in depth)

**Comment by sys9kdr** [comment]
@Fbrisset We still can't install 3.1.2 because URL strings missing arch info(arm64 or x86_64). You should add arch info for **some versions that contains arch info in URL strings(maybe 3.1.2 or later)**.


- - - - 

My `uname -a`:

```
Darwin S-MacBook-Air.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64
```

Could you assign this issue to me? I'll send PRs to download the correct files.

**Comment by Fbrisset** [comment]
@sys9kdr The issue is assigned. 
I have to rewrite all the version management: 
 - before version 2.0, you cannot install anything
 - after 2.0 you can install the Linux amd64 version
 - from 2.0.3 the MacOs amd64 version is available
 - 2.2.3 has no executable
 - 2.8 the arch is specified for the Linux version
 - 2.12 arch arm64 is available for Linux
 - 3.1.2 arch arm64 is available for macOS

Taking into account that the arch is specified only from version 3.1.2

**Comment by sys9kdr** [comment]
@Fbrisset okay, I'll write version management part. Please wait my PRs.
